# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beef-layout}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve England"]
  s.date = %q{2010-02-18}
  s.email = %q{steve@wearebeef.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "beef-layout.gemspec",
     "generators/layout_files/layout_files_generator.rb",
     "generators/layout_files/templates/application_layout.html.erb",
     "generators/layout_files/templates/public/javascripts/Gotham_Medium_500.font.js",
     "generators/layout_files/templates/public/javascripts/application.js",
     "generators/layout_files/templates/public/javascripts/cufon-yui.js",
     "generators/layout_files/templates/public/stylesheets/forms.css",
     "generators/layout_files/templates/public/stylesheets/ie6.css",
     "generators/layout_files/templates/public/stylesheets/ie7.css",
     "generators/layout_files/templates/public/stylesheets/layout.css",
     "generators/layout_files/templates/public/stylesheets/lightwindow.css",
     "generators/layout_files/templates/public/stylesheets/mobile.css",
     "generators/layout_files/templates/public/stylesheets/print.css",
     "generators/layout_files/templates/public/stylesheets/reset.css",
     "generators/layout_files/templates/public/stylesheets/skin.css",
     "generators/layout_files/templates/public/stylesheets/textile-editor.css",
     "generators/layout_files/templates/public/stylesheets/typography.css",
     "generators/layout_files/templates/public/stylesheets/wireframe.css",
     "lib/layout.rb",
     "rails/init.rb",
     "test/layout_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/beef/Layout}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generates basic beef layout}
  s.test_files = [
    "test/layout_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

